### ISSUE TITLE
Clarification of Powerwall Automation Documentation

### ISSUE THREAD

**Issue by eJonny** [netzero-labs/netzero#1]
Is my interpretation of the API below correct? Would it be helpful to update the readme?

operational_mode: Select either autonomous **_(the same as Time-Based Control in the Tesla app which means the system will look at the power rates defined in the Tesla app, Powerwall charge levels, and try to minimize the total cost of power, but it will not directly take into consideration the cost of "non-bypassable charges"_**) or self_consumption **_(the same as Self-Powered in the Tesla app: which means use power from solar and Powerwall and then use grid power)_**.
energy_exports: Options are pv_only (export solar only), battery_ok (export everything), or never (no export).
grid_charging: Select either true or false.

**Comment by zigam** [comment]
Yes, thanks for fixing this in #2.
