### ISSUE TITLE
Grid charging option suggests its disabled instead of enabled

### ISSUE THREAD

**Issue by nickz98** [netzero-labs/netzero#16]
Using my ios version of your app.
Within your app the 'grid charging' option 
has a button that suggests the feature is disabled when in fact it's enabled.
If I correlate the option to the entry that is seen from the Tesla app you can see how its misleading.
I guess you just need to change the word 'Disabled' to 'Enabled'?

![20240515_135457317_iOS](https://github.com/netzero-labs/netzero/assets/168316760/e760be2a-c76f-410b-a2da-cf13a9c040f1)
![20240515_135529754_iOS](https://github.com/netzero-labs/netzero/assets/168316760/5e6290ea-9caa-41e6-b327-fbc7424a1b98)

**Comment by zigam** [comment]
Thanks for the report, the label is indeed incorrect.  I fixed this and it will make its way into the next release.

**Comment by zigam** [comment]
Independently from the bug, I also realize a changing label next to a switch is confusing, I'll change that to a toggle similar to Tesla's.

**Comment by zigam** [comment]
The label is fixed in version 1.82, available in the app stores.  You might need to update manually, since the version is still rolling out.
