### ISSUE TITLE
Incorrect Utility Rate show in App

### ISSUE THREAD

**Issue by GNG007** [netzero-labs/netzero#18]
Previously I had the Amber utility rates associated to my account, working as expected and translating to the Tesla Powerwall settings.

Recently the Netzero App is showing Octopus Energy's Agile Octopus as my utility Rate and i cannot reset or revert it back to the Amber Utility rates.

**Comment by zigam** [comment]
Thanks for the report, I responded to your email about this issue. I'll improve the logic for showing eligible utilities.
