### ISSUE TITLE
iOS App v2 - Monitoring tab strip won't scroll to the right

### ISSUE THREAD

**Issue by eJonny** [netzero-labs/netzero#42]
After establishing connection to my Gateway 2, I can’t scroll right to Gateway (it just rubber bands back) after in Monitoring and Diagnostics.

Also, if String data isn't available (because I have the Tesla Inverter and PW2s), could the Stings tab be hidden? It just gives me FOMO for the PW+ peeps.

![image](https://github.com/user-attachments/assets/40bd7696-94fa-4821-91f5-eee67202ce19)

**Comment by zigam** [comment]
Thanks for the report, both fixed and will go out with the next TestFlight release.
