### ISSUE TITLE
Android app 2.0.0 (beta) - Temperature in header displayed in Fahrenheit

### ISSUE THREAD

**Issue by BJReplay** [netzero-labs/netzero#43]
I am in Australia, and can't specify the UoM for temperature, but not being in the US of A, don't want Freedom Units, but Celcius.

When I specify my location (I chose `<my suburb>`, AU and hit enter, and the app correctly auto corrected to my suburb, post-code, Australia), and similarly, if I choose Melbourne, AU, and hit enter, the app correctly auto-corrects to Melbourne VIC, Australia, so it knows where I am and fetches the correct weather, but doesn't choose the default locale units.

To be fair, a lot of other apps don't either.

System default language is English (Australia)

I'm not sure if it's possible to determine a system default temperature unit, or whether it is necessary to allow the UoM to be chosen as it can be for many weather apps.
![Screenshot_20241026_152258_Netzero](https://github.com/user-attachments/assets/317f143e-cc4e-49d2-bd13-2b9a6fd34b3c)
![Screenshot_20241026_152326_Netzero](https://github.com/user-attachments/assets/44e4d17b-af2b-4220-9304-e34b165e1943)

**Comment by zigam** [comment]
Thanks for the report, fixed and will go out with the next release.
