### ISSUE TITLE
Tomato.Energy

### ISSUE THREAD

**Issue by vcbadboy** [netzero-labs/netzero#44]
Do you have any plans to support tomato.energy in the UK. I’ve just switched and hoping to continue benefitting from the utility update

PS love this app, I’ve been using it with octopus and it’s just fantastic, thank you

**Comment by zigam** [comment]
Thanks for the feedback!

Do you know if tomato.energy has an API for developers to access their Agile rates? I couldn't find it.

**Comment by vcbadboy** [comment]
I’ll email their customer relations team to ask and get back to you

**Comment by zigam** [comment]
Feel free to reopen this once you hear back from tomato.energy.
