### ISSUE TITLE
MPPT Tracking?

### ISSUE THREAD

**Issue by profdraper** [netzero-labs/netzero#46]
Seems odd the the PW3 provides no options for MPPT tracking & unlike some other inverter brands.
I wonder if this functionality could be explored or activated in NetZero? Thanks.

**Comment by zigam** [comment]
Tesla made diagnostics access much harder for Powerwall 3, but it is possible. Netzero will require a few changes before the data is available.

Diagnostics for Powerwall 3 will require scanning the QR code behind the Powerwall 3 cover. It's best to take a picture of that QR code when the Powerwall is being installed or serviced. If that's not an option, you might be able to get the password from Tesla Support.

One you get the password, you can use the Tesla One app to access diagnostics (and soon, Netzero).

**Comment by profdraper** [comment]
Thanks for this, appreciated. Yes, I have tried a couple of times to log-in via bar code but does not work (& as many others have reported on various fora). Will see if I can obtain that from our solar installers.

**Comment by zigam** [comment]
The latest version of the Netzero app (2.0.2) has support for Powerwall 3 diagnostics. You might need to update the app manually from the App Store, since it's still rolling out.

**Comment by profdraper** [comment]
Good to see thanks so much for the update, a couple of observations:
Your advice re. login to Tesla One all worked, shows  MPPT info for my PW3 & that app will indeed re-connect again later with Network name & PW but needs to be very close by the the PW.

2.02 Netzero does so as well & seems to provide more details again on Strings vs. Tesla One's MPPT. For my solar array, Tesla One shows data for two MPPTs whereas Netzero shows data for 4 Strings (& two disabled). Not sure why the difference here, but seems I get more from Netzero.

A couple of other oddities: 
Once Tesla One has been connected up the first time, the app can connect again after that with the PW obtained from under the PW3 cover. 

No so with Netzero for now: it always wants to be very close to the PW3 and wants only the QR code (will not accept Network & PW). Removing & replacing the cover is a drag obviously, so I made a Pic of the QR code & which works fine, but Netzero wants to re-log in every time to access the Diagnostics, does not retain the earlier figures, and also must be right next to the PW3 to do so.

Still, very nice thank you, appreciated. I hope this is useful.

**Comment by zigam** [comment]
Thanks for the feedback!

I'm surprised the were differences in the MPPT output, did you collect the data from the two apps at the same time? It's possible some strings were inactive if the sun wasn't up.

Both Tesla One and Netzero have to connect to the PW3 built-in Wi-Fi, so you need to be close. I'm not sure why Netzero would be any different here.

I'll check why Netzero didn't save the network name and password though, that should have happened.

**Comment by profdraper** [comment]
Yes I did collect the data at the same time.

**Comment by profdraper** [comment]
Yes, I did collect the data at the same time, pics here:Apologies, yes i need to be close to the PW in both cases, but also yet, Netzero cannot use the log/pw again, needs the QR code.CheersOn 8 Nov 2024, at 14:51, Ziga Mahkovec ***@***.***> wrote:﻿
Thanks for the feedback!
I'm surprised the were differences in the MPPT output, did you collect the data from the two apps at the same time? It's possible some strings were inactive if the sun wasn't up.
Both Tesla One and Netzero have to connect to the PW3 built-in Wi-Fi, so you need to be close. I'm not sure why Netzero would be any different here.
I'll check why Netzero didn't save the network name and password though, that should have happened.

**Comment by zigam** [comment]
Looks like the pics didn't get through, maybe you can send them to feedback@netzero.energy

Thanks!

**Comment by profdraper** [comment]
Yes, we're in Australia, 230v 50Hz.

3 x MPPTs here but each at higher current than the 6 in the US model, 

Maximum Solar STC Input: 20 kW
Withstand Voltage: 600 V DC
PV DC Input Voltage Range: 60 - 550 V DC
PV DC MPPT Voltage Range 60 - 480 V DC
MPPTs: 3
Maximum Current per MPPT (Imp): 26A
Maximum Short Circuit Current per MPPt (Isc): 30A

Model Number: 1707000-xx-y 
Nominal Grid Voltage (Input & Output): 230VAC
Grid Type: Single Phase
Frequency: 50Hz
Nominal Battery Energy: 13.5 kWh AC
Nominal Output Power (AC): 5 kW 10 kW
Maximum Apparent Power: 5,000 VA 10,000 VA
Maximum Continuous Current: 21.7 A 43.5 A
Overcurrent Protection Device: 32 A 50 A
Maximum Continuous Charge Power: 5 kW

**Comment by zigam** [comment]
To follow up here: I believe the differences in MPPT output are actually a Tesla One issue. The UK/Australia version of PW3 has 3 MPPT ports, but under the hood they look like 6 ports with paralleled strings (this allows for the higher current in this version of PW3). From what I've seen, the data in Netzero is more accurate than Tesla One.
