### ISSUE TITLE
Octopus Intelligent Go

### ISSUE THREAD

**Issue by craigmase** [netzero-labs/netzero#48]
Hi first of all I love the app

When I set the utility plan to OIG everything seems to worth fine with the automation but the Powerwall 2 is exporting too early (generally between 3-7pm) to where the SOC drops to low then I'm forced to use the grid which is undoing all the export I've gained during the day. 

Ideally I'd want to retain the SOC until say 9pm then start to export ending up a 0 at 11:30pm

**Comment by craigmase** [comment]
These are the automations I've created to try a stop this happening. 

![image](https://github.com/user-attachments/assets/3d8cf4ac-be55-4e60-8c69-819a7c091b6f)

**Comment by zigam** [comment]
Thanks for the report. Did the automations help with the problem?

Powerwall behavior in Time-Based Control is determined by Tesla, Netzero just provides the up-to-date tariffs. I'm actually surprised it would export on OIG, I assume you have a fixed export price? It seems avoiding pulling from the grid at the high daily rate would be more important than exporting at a fixed price.
