### ISSUE TITLE
Solar forecast Graphic on iPad wrong while on iPhone „correct“.

### ISSUE THREAD

**Issue by Elektron79** [netzero-labs/netzero#50]
The Solar forecast Graphic on the iPad shows always a sin Wave like distribution over the day.
If I compare this with the graphic shown on my iPhone, I can see that there the distribution over the day is more like the real distribution.

iPad is on iOS 16.7.10
iPhome is on iOS 18.1

**Comment by zigam** [comment]
Thanks for the report. There were some changes in the solar estimates recently, and they're not updated automatically. If you go to the Solar Estimates screen, wait for the estimate to be computed, and tap Done, they will refresh. Doing this on both devices should bring them back in sync.
