### ISSUE TITLE
No Wall connector configured 

### ISSUE THREAD

**Issue by 123childre** [netzero-labs/netzero#63]
I've recently started using the Net Zero app for monitoring our Powerwall etc.
I had to delete it he app and reinstall, but now the I can't see the EV option and have the message " No wall connector configured".
Everything seems to be setup in the Tesla app with access allowed for Net Zero.
Any suggestions how to figure the wall connector again in Net Zero.

Cheers 
Steve

**Comment by zigam** [comment]
For the EV charging integration, the Wall Connector has to be added to your Tesla energy system. When that's set up, the Tesla app will show a garage and Wall Connector on the home energy screen (with solar & Powerwall).

You should be able to add your Wall Connector to the energy system using the Tesla app's top-left dropdown, Add Product. If that doesn't work, Tesla Support can help with "merging" the two systems.
