### ISSUE TITLE
Unable to add solar array

### ISSUE THREAD

**Issue by grantmassie** [netzero-labs/netzero#7]
When trying to add a solar array using the app (iPhone app v1.67) the app crashes.

When trying to add a new solar array in the web app, clicking the Add Array button is unresponsive.

**Comment by zigam** [comment]
Thanks for the report!  There was a problem with a recent change to sync these settings across devices.  The web app should be fixed now, please give it a try.
App fix will go out soon (but if you configure the arrays in the web version they should sync to your app too).
